### ISSUE TITLE
Ancient Joker

### ISSUE THREAD

**Issue by Lawgikill** [EFHIII/balatro-calculator#17]
**Description of the bug**
Use of Ancient Joker leads to the calculator to spin and never give any resulting optimal hands.

**Steps To Reproduce**
Add Ancient Joker as one of the Jokers you have. I haven't tested with *only* Ancient Joker, but at the time of trial -- here was my setup:
https://efhiii.github.io/balatro-calculator/?h=oACuUoALzoABwH9qAADJFAAwAAzA6CEFwHgaAHAAHAALAARAAkABIACwAHAANAAR
See for yourself.

Removing Ancient Joker allowed the calculator to resume and work.

**Comment by Lawgikill** [comment]
NEVERMIND. I guess it's been fixed as of last night.

**Comment by EFHIII** [comment]
Yeah, this was reported on Reddit:
https://www.reddit.com/r/balatro/comments/1b4u2r1/comment/kus2npg/?context=3
