### ISSUE TITLE
Sometimes Baron and Steel cards are giving suboptimal results

### ISSUE THREAD

**Issue by emerald000** [EFHIII/balatro-calculator#2]
Here's a situation where it happened:

https://efhiii.github.io/balatro-calculator/?h=gAA2DAAHMCYPQeq1AKAAFA

It optimizes to AAKK which is worth 246 chips. If you manually change the hand to AAQQ, the score jumps up to 830 chips.

If you put Two Pairs to level 1 instead of 2, it correctly optimizes to AAQQ.

**Comment by EFHIII** [comment]
That bug was harder to track down than I was expecting, but it should be fixed now.
