### ISSUE TITLE
"Play hand" button

### ISSUE THREAD

**Issue by EFHIII** [EFHIII/balatro-calculator#20]
**Is your feature request related to a problem? Please describe.**
Making all of the changes after a hand can be annoying if that's the use-case being used.

**Describe the solution you'd like**
Change state values to reflect what they'd be after the hand was played.
e.g. remove played cards from hand, disable DNA if applicable, increment the current hand's number of times played.

**Additional context**
https://github.com/EFHIII/balatro-calculator/issues/8#issuecomment-1997768081

**Comment by Lawgikill** [comment]
And... if you do implement this, you'd also have to do a "undo play hand", or something similar, to roll it back.

**Comment by EFHIII** [comment]
The `Clear hand` button should resolve this.
