### ISSUE TITLE
Card Modifier Selectors Dissapear at Different Zoom Levels

### ISSUE THREAD

**Issue by WilsontheWolf** [EFHIII/balatro-calculator#21]
**Description of the bug**
At different zoom levels (I assume screen widths), the modifiers for playing cards disappear.

**Steps To Reproduce**
I can replicate it on FireFox with the responseive design mode, by setting the screen resolution at 1280 x 800 (the Laptop with MDPI Screen preset), and going to the cards tab. This does also happen at my laptop's native resolution which I think is 1805 pixels wide. Zooming in and out seems to also cause it to appear and disappear.

**Expected behavior**
It should show at all times

**Screenshots**
![image](https://github.com/EFHIII/balatro-calculator/assets/33164598/1b647b84-b3fa-4033-bc33-ed0390da84a3)

https://github.com/EFHIII/balatro-calculator/assets/33164598/7d679585-a18c-44a2-be20-a110858bfe1b

**Comment by EFHIII** [comment]
This seems to be related to how Firefox handles CSS flexboxes.
I don't know how to fix this and am open to suggestions.

**Comment by WilsontheWolf** [comment]
It seems adding `width: 100%;`  here https://github.com/EFHIII/balatro-calculator/blob/main/index.html#L99 seems to fix it and not break it on chrome. This does feel a little hacky, so I'll let you decide if its the best behaviour. I'll see if theres some other solution I can find.

**Comment by EFHIII** [comment]
That didn't seem to fix it on my end. Could you make a PR?
