### ISSUE TITLE
Queen Rank Location

### ISSUE THREAD

**Issue by Lawgikill** [EFHIII/balatro-calculator#25]
**Description of the bug**
Why do queens always appear all the way on the left even though as a rank, they are supposed to go in between Kings and Jacks? Even if you have Aces or Kings in hand, a Queen will always appear all the way on the left.

**Comment by EFHIII** [comment]
This is intentional.
The point is so that Shoot the Moon (when it is present) triggers before steel cards

**Comment by Lawgikill** [comment]
But wouldn't the presence of Shoot the Moon + "Optimize Hand" move Queens over to the left? You don't seem to arbitrarily re-order things "in case something is there" if it isn't. This looks like the only case where you do?

**Comment by Lawgikill** [comment]
You say that... but I know that's not the case. Take what you do for Raised Fist Joker as an example. Cards in hand are ordered accordingly.

**Comment by Lawgikill** [comment]
I mean, I know that Raised Fist doesn't generally care the order of cards in hand. I just notice specifically that you order the cards in hand because of the presence of Raised Fist. That's all I'm saying about the Queens in hand. It's only there and ordered differently for the presence of Shoot the Moon. Wouldn't it be easy to do something like:
if Shoot the Moon then Queens on left?

**Comment by EFHIII** [comment]
> Wouldn't it be easy to do something like: if Shoot the Moon then Queens on left?

It would be possible, but not the most straightforward because of how it's handled as an edge case. It's definitely not a bug though.

**Comment by Lawgikill** [comment]
Yea, totally fair. Not a big deal either way, just something I noticed was odd.
