### ISSUE TITLE
Optimize Hand / Hand Order

### ISSUE THREAD

**Issue by Lawgikill** [EFHIII/balatro-calculator#28]
**Description of the bug**
I *think* this is a bug. I noticed that multipliers in hand in "any" order don't cause the score to change.

**Steps To Reproduce**
https://efhiii.github.io/balatro-calculator/?h=YADSFyFGJAAVyYADpzQAFSJAAtNColgIwU0EQHAcAgADgACgAFAACgAF

**Expected behavior**
Moving glass card to the right/left of polychrome cards - shouldn't that change the score? It doesn't. However, the score itself IS the optimized score. It just doesn't show the hand in the order it's supposed to.

**Comment by EFHIII** [comment]
No. multiplication is commutative. The order only matters if you're mixing +mult with Xmult, e.g. 
https://efhiii.github.io/balatro-calculator/?h=YADSFyFGJAAVyYADpzQAFSJAAsYLBU0KiU0EQHAcAgADgACgAFAACgAF

**Comment by Lawgikill** [comment]
lol. Duh, that does make sense. My fault.
