### ISSUE TITLE
Raised Fist Joker

### ISSUE THREAD

**Issue by Lawgikill** [EFHIII/balatro-calculator#29]
**Description of the bug**
Raised Fist Joker doesn't play extra cards to get rid of them from hand.

**Steps To Reproduce**
https://efhiii.github.io/balatro-calculator/?h=QABBDYBAAwwJgLA5B0CIFAE
Optimize Hand shows the 3 of a kind (8s) alone, but playing the 2 and 3 with it will raise the score.

**Comment by Lawgikill** [comment]
Oh interesting. I'm also noticing that Raised Fist will also generate a "Queen double" that's not actually there. Something for you to look into. For example:
With Raised Fist present, disable Optimize Hand, and a blank hand. Add a Queen. You'll see 2 of them appear instead of 1. The 2nd one isn't actually "there". Even if you Optimize Hand, it'll give you 1 Queen with High Card.

**Comment by Lawgikill** [comment]
More issues noticed with Raised Fist - it's just inaccurate. Take a look at this hand, for example:
https://efhiii.github.io/balatro-calculator/?h=QABBDYBAAOYIwMA4AKAEHwDg

Optimize Hand says to play 2 pair, Aces and nines. If you play Aces and 3s, it's more points due to Raised Fist.

**Comment by EFHIII** [comment]
The double queens appears to be a bug related to if the lowest card type is a queen, both the code for Raised Fist and Shoot the Moon put them in the deck.

There are only 3 queens here:
https://efhiii.github.io/balatro-calculator/?h=QABBDYCAAAYJQKgFUA

**Comment by EFHIII** [comment]
fixing #34 fixed the initial part of this issue, but not the doubling of queens.
