### ISSUE TITLE
Flower Pot should only trigger on scoring cards

### ISSUE THREAD

**Issue by emerald000** [EFHIII/balatro-calculator#3]
Flower Pot currently triggers if there are played cards of each suit. It should only trigger if there are scored cards of each suit.

**Comment by EFHIII** [comment]
The way I have things now, it would be difficult to make that work, but I'm currently in the process of rewriting the entire scoring engine, so I'll keep that in mind.

**Comment by Draco18s** [comment]
Hanging Card does the same thing.
![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/9d67ba7d-c19b-44b4-9772-4c2744d98a22)
![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/71861184-c927-424b-b1b1-5803ba0d92c5)
