### ISSUE TITLE
Baseball Joker counts itself as Uncommon

### ISSUE THREAD

**Issue by Draco18s** [EFHIII/balatro-calculator#33]
https://efhiii.github.io/balatro-calculator/?h=YAAZVAAYGDKzgAVAyFAADsBAAKAsBQADASAwCwEQA4ABQADQAFAAFAAH
![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/ba1cbf96-270a-4b6b-878b-62d99b975fe5)

Calculator says this should result in just over a million points, however, it actually scores 693k

![20240317140908_1](https://github.com/EFHIII/balatro-calculator/assets/1750680/82232ce3-a402-4c19-a1d5-0b8fecb74713)
Hologram at 4.5X, Glass at 1.5, Cowboy Boots should be +5 (not +7) as screenshot was taken after the two gold cards triggered.

The breakdown seems to look like it's ~~counting the polychrome multiple times~~ (ah no, just the card face is missing) the Baseball Card (a Rare joker) counting itself.
![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/d8340c92-eefa-4ae9-a23a-20f53cb0ed76)

Discounting that extra 1.5X does reduce the score to the correct value (simulated by dropping Glass down a value point).
![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/bdef2300-285e-4e7a-ac68-4aa193bf6ebe)

**Comment by EFHIII** [comment]
This seems to be related to blueprint/brainstorm copying an uncommon joker
here's a simpler cases showing the bug:
https://efhiii.github.io/balatro-calculator/?h=wACM53B2
and just changing the joker order (which shouldn't effect the sore) doesn't show the bug
https://efhiii.github.io/balatro-calculator/?h=wACM47Du
