### ISSUE TITLE
Poor optimize hand result

### ISSUE THREAD

**Issue by Draco18s** [EFHIII/balatro-calculator#34]
![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/f7e90e0b-e34c-4a9d-a3cc-d926db5a0b43)

With the extra 7 (created with a Cryptid after checking hand, so updated the calculator). Swapping it for the Steel Queen, it scores higher.

![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/d2846518-cdb4-48f1-b309-5783834ebdc4)

**Comment by EFHIII** [comment]
Possibly related to https://github.com/EFHIII/balatro-calculator/issues/29#issuecomment-2002007874
