### ISSUE TITLE
Ice Cream Joker + Play Hand

### ISSUE THREAD

**Issue by Lawgikill** [EFHIII/balatro-calculator#38]
At this point, since you have the Play Hand button, you might as well increase Ice Cream Joker when you use it.

**Comment by EFHIII** [comment]
I got all of the ones that have the text "(Currently ___)" but missed a few others. I believe:
Loyalty Card, The Idol, and Ice Cream.

I suppose Turtle Bean could also be tracked.

**Comment by Lawgikill** [comment]
Loyalty Card too maybe?

**Comment by EFHIII** [comment]
I said loyalty card

**Comment by Lawgikill** [comment]
My fault.

**Comment by EFHIII** [comment]
Ice Cream, Popcorn, and Turtle bean will become disabled when in-game they'd disappear. I think that's helps make it clear enough what's going on where suddenly having the cards disappear might be confusing.
