### ISSUE TITLE
Spare Trousers + Baseball Card

### ISSUE THREAD

**Issue by Lawgikill** [EFHIII/balatro-calculator#40]
**Description of the bug**
I don't think your Spare Trousers Joker is appropriately flagged as an Uncommon joker, because it doesn't trigger with Baseball Card joker.

https://efhiii.github.io/balatro-calculator/?h=oADyQQAZkFgGSIAB2AgAVDAhgRA0BQHxOAAABQADgABQABQACgAFAAE4AAA4AA8AADYADgADgA

**Comment by Lawgikill** [comment]
This still isn't fixed.

**Comment by EFHIII** [comment]
Whoops... You only said spare trousers was broken so I assumed that's what the bug was but the entire last row of joker rarities was missing.
