### ISSUE TITLE
Lucky Cat

### ISSUE THREAD

**Issue by Lawgikill** [EFHIII/balatro-calculator#43]
**Description of the bug**
Having Lucky Cat freezes the calculator entirely. Cards can't be added, hands can't be optimized, etc.

**Comment by EFHIII** [comment]
Can lucky cards trigger both the money and mult or just one at a time?

**Comment by Lawgikill** [comment]
It CAN trigger both, but when it does, Lucky Cat only activates once.

**Comment by EFHIII** [comment]
The above commit reflects what you claim it does.
