### ISSUE TITLE
Clear Hand doesn't reset "played this round" check

### ISSUE THREAD

**Issue by Draco18s** [EFHIII/balatro-calculator#45]
![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/35fd570a-7b81-4b7a-92a2-5ed3340d09b4)
![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/909ae59e-8d15-42f6-bffc-544753e4118d)

"Number of cards in hand" also doesn't reset to 0/8

**Comment by EFHIII** [comment]
It wasn't meant to, but I guess it makes sense to expect it to.

**Comment by EFHIII** [comment]
The number of cards in hand is just a visual thing, but I guess I can fix that.
