### ISSUE TITLE
Optimize Hand checkbox at a certain hand size?

### ISSUE THREAD

**Issue by Lawgikill** [EFHIII/balatro-calculator#46]
**Description of the bug**
At a certain hand size -- I think it's 9 cards -- the Optimize Hand checkbox immediately toggles. So it will go on if it was off before and it will turn off if it was on before. Is this intentional? I'm guessing no. If it were up to me, I'd want it to never toggle on/off automatically without my input.

**Comment by EFHIII** [comment]
It doesn't toggle on; only off.
See #47
