### ISSUE TITLE
Fibonacci Joker doesn't account to Aces

### ISSUE THREAD

**Issue by Zarrrah** [EFHIII/balatro-calculator#5]
Noticed the calculator would show some sub-optimal hands when I had Fibonacci. When manually selecting Aces the breakdown doesn't show Fibonacci triggering.

**Comment by Draco18s** [comment]
Came here just to report this too.
![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/9d67ba7d-c19b-44b4-9772-4c2744d98a22)
![image](https://github.com/EFHIII/balatro-calculator/assets/1750680/354377ea-eb66-4aae-8539-038a90d05591)

**Comment by EFHIII** [comment]
I'm in the middle of a complete rewrite of the simulation engine, and I already had it fixed in the rewrite, but I added a short-term fix for the old engine for in the meantime, so it should be good now.
