### ISSUE TITLE
What does the "long-term EV"mean?

### ISSUE THREAD

**Issue by FENGFU202403** [EFHIII/balatro-calculator#56]
I use the balatro-calculator,
When I choose Rank 2,why is the result is 14?
and even is up to 42?
I don't understand the mean of "long-term ev".
Please help!
![企业微信截图_17117118641129](https://github.com/EFHIII/balatro-calculator/assets/165445748/a13e196b-9d5e-4dce-aff0-44af302b4299)

**Comment by Draco18s** [comment]
Long Term Expected Value
The short term EV is going to assume it doesn't pop right now, but long term EV is based on its average pop rate.

**Comment by EFHIII** [comment]
Long-term EV (expected value) is the mean
short-term EV is the median
