### ISSUE TITLE
Weird visual bug

### ISSUE THREAD

**Issue by Draco18s** [EFHIII/balatro-calculator#63]
Not sure what it is about this set of cards, but manually playing a pair with two unscored cards (to raise the value of Raised Fist) results in some held cards visually disappearing.

![balatro-what](https://github.com/EFHIII/balatro-calculator/assets/1750680/62ea3fe3-f9de-492a-b75d-125b6e6dbf50)

**Comment by jimmythebass** [comment]
I had this same bug with Raised Fist without any manual adjusting

**Comment by EFHIII** [comment]
I believe it is fixed now. Let me know if you run into similar problems still.
