### ISSUE TITLE
Update to include changes in 1.0.1f

### ISSUE THREAD

**Issue by BNTFryingPan** [EFHIII/balatro-calculator#65]
Balatro released a new update (As of writing this, its live on Steam, but not on consoles yet), with various balance changes. This update makes the calculator slightly inaccurate as some of the jokers have changed.

patch notes are available [on steam](https://steamcommunity.com/games/2379780/announcements/detail/4208127528883891676)

**Comment by BNTFryingPan** [comment]
didnt follow the issue template because it doesnt really apply here

**Comment by EFHIII** [comment]
I was already aware; have been busy with other stuff and don't want to break the calculator for the consoles so it'd need a way to select what version you're running (probably default to current steam version). Anyway, that's a lot of work, maybe I'll get to it, but I don't know when.

**Comment by simonstey** [comment]
fwiw, consoles are now on 1.0.1f too, so no version toggle necessary.
