### ISSUE TITLE
Mad Joker card is different

### ISSUE THREAD

**Issue by HazMasterFlash** [EFHIII/balatro-calculator#67]
**Describe the Issue**
I've been using this, and it is quite good, but there is a difference in the calculator and my game: My Mad Joker is a different card to yours.
Mine is: "+10 Mult if played hand contains a Two Pair"
Your one is: "+20 Mult if played hand contains a 4 of a Kind."

**Describe the solution you'd like**
I would like this to be put into your calculator so it can be used in the calculator properly.

**Describe alternatives you've considered**
You might still be able to add it in as another Joker card instead of replacing your own version.

**Additional context**
I do not know whether this is version specific, but for context I am playing version 1.0.1 - FULL on PS5
Added 2 Screenshots for proof that I do have those cards (Mad_Joker_1 is to show the card, Mad_Joker_2 is if you need it for assets etc.)
![Balatro_Mad_Joker_1](https://github.com/EFHIII/balatro-calculator/assets/170449317/662aff65-3274-4601-b948-3cb4f0bbf91f)
![Balatro_Mad_Joker_2](https://github.com/EFHIII/balatro-calculator/assets/170449317/f7daa1ef-aed1-4d6b-ac29-909c1f912494)

**Comment by BNTFryingPan** [comment]
Is this still an issue after #68 ?

**Comment by EFHIII** [comment]
no
