### ISSUE TITLE
Ability to enable or disable jokers from hand without removing them

### ISSUE THREAD

**Issue by sielerjm** [EFHIII/balatro-calculator#73]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a problem, but would improve the efficiency of the calculator.

**Describe the solution you'd like**
I'd like to be able to keep more than 5 or 6 jokers in my build/hand, but have the ability to temporarily  disable or enable jokers to test out different joker set combinations without needing to re-find and reset each of their values or order in my hand. 

**Describe alternatives you've considered**
N/A

**Additional context**
This feature would be similar to how you can add or remove cards that you're holding to your playing hand, but instead with the jokers. I did a rough mock-up of what I'm envisioning below:

<img width="400" alt="Balatro__Before" src="https://github.com/user-attachments/assets/98b2550c-9347-4c31-b285-d5438463a00c">
<img width="400" alt="Balatro__After" src="https://github.com/user-attachments/assets/4cb4f055-2ec1-47ad-a135-67044c36a33b">

PS. Thank you for the incredibly useful tool!

**Comment by EFHIII** [comment]
This is already a feature via the "does not trigger" edition of jokers, which you can enable/disable when a joker is selected.
![image](https://github.com/user-attachments/assets/2c5404bf-ce36-44ad-bfb4-eaf58adad936)
