### ISSUE TITLE
Ability to edit compounding Joker values

### ISSUE THREAD

**Issue by zmm2025** [EFHIII/balatro-calculator#75]
It would be useful to be able to edit certain properties of Jokers that are variable. Looking at [the wiki](https://balatrogame.fandom.com/wiki/Jokers), I believe this would apply to the following Jokers:

[Joker Stencil](https://balatrogame.fandom.com/wiki/Joker_Stencil), [Ceremonial Dagger](https://balatrogame.fandom.com/wiki/Ceremonial_Dagger), [Steel Joker](https://balatrogame.fandom.com/wiki/Steel_Joker), [Ride the Bus](https://balatrogame.fandom.com/wiki/Ride_the_Bus), [Runner](https://balatrogame.fandom.com/wiki/Runner), [Ice Cream](https://balatrogame.fandom.com/wiki/Ice_Cream), [Blue Joker](https://balatrogame.fandom.com/wiki/Blue_Joker), [Constellation](https://balatrogame.fandom.com/wiki/Constellation), [Green Joker](https://balatrogame.fandom.com/wiki/Green_Joker), [To Do List](https://balatrogame.fandom.com/wiki/To_Do_List), [Card Sharp](https://balatrogame.fandom.com/wiki/Card_Sharp), [Red Card](https://balatrogame.fandom.com/wiki/Red_Card), [Madness](https://balatrogame.fandom.com/wiki/Madness), [Square Joker](https://balatrogame.fandom.com/wiki/Square_Joker), [Vampire](https://balatrogame.fandom.com/wiki/Vampire), [Hologram](https://balatrogame.fandom.com/wiki/Hologram), [Obelisk](https://balatrogame.fandom.com/wiki/Obelisk), [Erosion](https://balatrogame.fandom.com/wiki/Erosion), [Fortune Teller](https://balatrogame.fandom.com/wiki/Fortune_Teller), [Stone Joker](https://balatrogame.fandom.com/wiki/Stone_Joker), [Lucky Cat](https://balatrogame.fandom.com/wiki/Lucky_Cat), [Bull](https://balatrogame.fandom.com/wiki/Bull), [Flash Card](https://balatrogame.fandom.com/wiki/Flash_Card), [Popcorn](https://balatrogame.fandom.com/wiki/Popcorn), [Spare Trousers](https://balatrogame.fandom.com/wiki/Spare_Trousers), [Ancient Joker](https://balatrogame.fandom.com/wiki/Ancient_Joker), [Ramen](https://balatrogame.fandom.com/wiki/Ramen), [Castle](https://balatrogame.fandom.com/wiki/Castle), [Campfire](https://balatrogame.fandom.com/wiki/Campfire), [Acrobat](https://balatrogame.fandom.com/wiki/Acrobat), [Swashbuckler](https://balatrogame.fandom.com/wiki/Swashbuckler), [Throwback](https://balatrogame.fandom.com/wiki/Throwback), [Glass Joker](https://balatrogame.fandom.com/wiki/Glass_Joker), [Wee Joker](https://balatrogame.fandom.com/wiki/Wee_Joker), [The Idol](https://balatrogame.fandom.com/wiki/The_Idol), [Hit the Road](https://balatrogame.fandom.com/wiki/Hit_the_Road), [Driver's License](https://balatrogame.fandom.com/wiki/Driver%27s_License), [Bootstraps](https://balatrogame.fandom.com/wiki/Bootstraps), [Canio](https://balatrogame.fandom.com/wiki/Canio), [Triboulet](https://balatrogame.fandom.com/wiki/Triboulet), and [Yorick](https://balatrogame.fandom.com/wiki/Yorick).

It's possible that I missed some, but as some examples, this change would allow the editing of [Runner](https://balatrogame.fandom.com/wiki/Runner)'s current Chips bonus, [Green Joker](https://balatrogame.fandom.com/wiki/Green_Joker)'s current Mult Bonus, [To Do List](https://balatrogame.fandom.com/wiki/To_Do_List)'s current Hand, [Card Sharp](https://balatrogame.fandom.com/wiki/Card_Sharp)'s current active status, [Madness](https://balatrogame.fandom.com/wiki/Madness)'s current Mult multiplier, [Erosion](https://balatrogame.fandom.com/wiki/Erosion)'s deck starting size, and [The Idol](https://balatrogame.fandom.com/wiki/The_Idol)'s current rank and suit.

This would help predict scores much more accurately. I ran into this conflict with Jokers of Blueprint and Yorick, which was at "Currently X14 Mult" in-game, but I the site couldn't let me edit it from X1 Mult, meaning Blueprint was arranged improperly and my score representation was missing a 196+ Mult multiplier.

**Comment by 1RedOne** [comment]
Wow, I ran into the same issue and came to make this same issue today.  I would say that today this is by far the best balatro calaulator I've found!

**Comment by EFHIII** [comment]
After clicking on a joker, you can edit its properties including its `value` (which means something slightly different for every joker). Its `value` is what you use to set the variable aspect of a joker's text.

In this example, the default state of stencil is 1X. The default value is always 0. I've set the joker's value to 4 so that increases it to 5X.
![image](https://github.com/user-attachments/assets/2cb7f8d0-338a-4bd3-9d01-b9b9be6cf8c2)

You can also edit the Joker's sell value (which usually isn't relevant but can be) and its edition. The red X edition disables the joker so that it won't trigger.

A similar thing works for Yorick and most every other Joker. (There may be one or two that don't quite work right)
